dependencies:
- name: postgresql
  version: ~0.11.2
  #repository: https://kubernetes-charts.storage.googleapis.com/
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
  tags:
    - devicehive-database

- name: kafka
  version: ~0.7.2
  #repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  repository: https://charts.helm.sh/incubator
  condition: kafka.enabled

- name: redis
  version: ~3.2.5
  #repository: https://kubernetes-charts.storage.googleapis.com/
  repository: https://charts.helm.sh/stable
  condition: mqttBroker.enabled
