javaServer:
  repository: devicehive
  #tag: 3.5.0
  tag: latest
  pullPolicy: IfNotPresent
  auth:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  backend:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: INFO
  frontend:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  hazelcast:
    minHeapSize: 512m
    maxHeapSize: 512m
    replicaCount: 1
    resources: {}
  plugin:
    enabled: false
    pluginConnectUrl: ""
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  # Connection method to Kafka
  # wsproxy: connect to Kafka via devicehive-ws-proxy, default
  # rpc: direct connection to Kafka
  bus: wsproxy

  ## JWT secret is used to sign and verify tokens
  ## If not set, a random 16 characters secret will be used
  jwtSecret: ""

ingress:
  enabled: true
  annotations: {}
  kubernetes.io/ingress.class: traefik
  hosts: ["hub-prod.devicethread.com"]

backendNode:
  enabled: false
  #https://hub.docker.com/r/devicehive/devicehive-backend-node/tags
  image: devicehive/devicehive-backend-node:development
  pullPolicy: IfNotPresent
  loggerLevel: info
  replicaCount: 1
  resources: {}

mqttBroker:
  enabled: false
  #https://hub.docker.com/r/devicehive/devicehive-mqtt/tags
  #image: devicehive/devicehive-mqtt:1.1.0
  image: devicehive/devicehive-mqtt:latest
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
    port: 1883
  appLogLevel: info

proxy:
  #https://hub.docker.com/r/devicehive/devicehive-proxy/tags
  #image: devicehive/devicehive-proxy:3.5.0
  image: devicehive/devicehive-proxy:development
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  ingress:
    enabled: true
    annotations: {}
    kubernetes.io/ingress.class: traefik
    hosts: ["hub-prod.devicethread.com"]

wsProxy:
  #https://hub.docker.com/r/devicehive/devicehive-ws-proxy/tags
  #image: devicehive/devicehive-ws-proxy:1.1.0
  image: devicehive/devicehive-ws-proxy:latest
  pullPolicy: IfNotPresent
  internal:
    replicaCount: 1
    resources: {}
  external:
    enabled: false
    replicaCount: 1
    resources: {}

nodeSelector: {}

rbac:
  create: true
  serviceAccountName: default

# External dependencies
# PostgreSQL
postgresql:
  enabled: false
  postgresDatabase: dh1
  postgresUser: devicehive
  postgresPassword: HZQtoOBeFxPhFOYtfSAs
  postgresHost: dh-test.cjj4wvruc8hl.us-west-1.rds.amazonaws.com
  postgresPort: 5432
  persistence:
    enabled: true
    size: 1Gi
  imageTag: 10

# Apache Kafka
kafka:
  enabled: true
  # enabled: false
  # kafkaServer: b-1.dhtest.dk0tbt.c4.kafka.us-west-1.amazonaws.com:9092,b-2.dhtest.dk0tbt.c4.kafka.us-west-1.amazonaws.com:9092
  # #zookeeperServer: 'z-2.dhtest.dk0tbt.c4.kafka.us-west-1.amazonaws.com:2181,z-3.dhtest.dk0tbt.c4.kafka.us-west-1.amazonaws.com:2181,z-1.dhtest.dk0tbt.c4.kafka.us-west-1.amazonaws.com:'
  # zookeeperServer: z-2.dhtest.dk0tbt.c4.kafka.us-west-1.amazonaws.com
  # zookeeperPort: 2181

# Redis for syncronization between MQTT brokers
redis:
  # MQTT broker doesn't support password auth with Redis so disable it
  usePassword: false
  host: dh-test.psapb0.clustercfg.usw1.cache.amazonaws.com
  port: 6379
